version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependabot
      - actions
    open-pull-requests-limit: 10
    reviewers:
      - issue-ops/maintainers

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependabot
      - npm
    open-pull-requests-limit: 10
    reviewers:
      - issue-ops/maintainers
