version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependabot
      - actions
    open-pull-requests-limit: 10
    reviewers:
      - issue-ops/maintainers
    groups:
      actions-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependabot
      - npm
    open-pull-requests-limit: 10
    reviewers:
      - issue-ops/maintainers
    groups:
      npm-development:
        dependency-type: development
        update-types:
          - minor
          - patch
      npm-production:
        dependency-type: production
        update-types:
          - patch
