#############################
## JavaScript Linter rules ##
#############################

env:
  node: true
  es6: true
  jest: true

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

ignorePatterns:
  - coverage
  - dist
  - linter
  - node_modules

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2023
  project:
    - tsconfig.eslint.json
  sourceType: module
  tsconfigRootDir: .

settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: tsconfig.eslint.json

plugins:
  - import
  - jest
  - prettier
  - '@typescript-eslint'

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:github/recommended
  - plugin:jest/recommended
  - plugin:prettier/recommended

rules:
  camelcase: off
  eslint-comments/no-use: off
  eslint-comments/no-unused-disable: off
  i18n-text/no-en: off
  import/no-namespace: off
  no-console: off
  no-shadow: off
  no-unused-vars: off
  prettier/prettier: error
