name: IssueOps Label Manager
description: Manage labels for issues and pull requests
author: Nick Alteen

branding:
  icon: check-square
  color: blue

inputs:
  action:
    description: The action to take
    required: false
    default: add
  api_url:
    description: The GitHub API URL to use
    required: false
    default: ${{ github.api_url }}
  create:
    description: Create the label(s) if not present
    required: false
    default: 'false'
  github_token:
    description: The GitHub API token to use
    required: false
    default: ${{ github.token }}
  labels:
    description: A line-separated list of labels to add or remove
    required: true
  issue_number:
    description: The issue or PR number
    required: true
    default:
      ${{ github.event.issue.number || github.event.pull_request.number }}
  repository:
    description: The repository to use
    required: false
    default: ${{ github.repository }}

runs:
  using: node20
  main: dist/index.js
