#############################
## JavaScript Linter rules ##
#############################

parser: '@typescript-eslint/parser'

env:
  node: true
  es6: true
  jest: true
  commonjs: true

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

ignorePatterns:
  - '!.*'
  - '**/node_modules/**'
  - '**/dist/**'
  - '**/coverage/**'
  - '**/.github/**'
  - '**/.vscode/**'
  - '*.json'

parserOptions:
  ecmaVersion: 2023
  sourceType: module
  project:
    - './.github/linters/tsconfig.json'
    - './tsconfig.json'

plugins:
  - 'jest'
  - '@typescript-eslint'

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:github/recommended
  - plugin:jest/recommended

rules:
  {
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/no-var-requires': 'off',
    'camelcase': 'off',
    'i18n-text/no-en': 'off',
    'import/no-commonjs': 'off',
    'import/no-namespace': 'off',
    'jest/no-conditional-expect': 'off',
    'no-console': 'off',
    'prettier/prettier': 'error'
  }
