name: Continuous Integration

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest

    permissions:
      contents: read
      statuses: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Check Format
        id: format-check
        run: npm run format:check

      - name: Lint
        id: lint
        run: npm run lint

      - name: Test
        id: test
        run: npm run ci-test
